name: jotrockenmitlocken
description: "Find out sth. interesting about me."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  url_launcher: ^6.1.8
  go_router: ^13.2.0
  markdown: ^7.2.1
  flutter_markdown: ^0.6.19
  flutter_markdown_latex: ^0.2.0
  provider: ^6.1.1
  csv: ^5.1.1
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_charts: ^24.2.6
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  mockito: ^5.4.4
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/barbell.png"
  min_sdk_android: 21 
  web:
    generate: true

  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Bewerbungsbilder/
    - assets/documents/
    - assets/documents/footer/
    - assets/data/

fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
